export const IDEAS_BY_CONTEXT = {
  "0-2:home": [
    "Peekaboo with colored scarves",
    "Tactile exploration with safe household items"
  ],
  "3-4:home": [
    "Sort toys by color challenge",
    "Animal moves mini-circuit"
  ],
};
export function generateIdeasStub({ageGroup, place, mood}){
  const key = `${ageGroup}:${place||"home"}`;
  const base = IDEAS_BY_CONTEXT[key] || IDEAS_BY_CONTEXT["3-4:home"] || [];
  return base.slice(0,4).map(t => ({ title: t, desc: "Idea generated by stub", mood: mood||null }));
}
